[package]
name = "rust_game"
version = "0.1.0"
authors = ["kyle"]
edition = "2018"

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"

[[bin]]
name = "rust"
path = "src/main.rs"

[[bin]]
name = "server"
path = "src/server.rs"